baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'graysx-hugo'

[params]
  logo = "assets/img/logo.webp"
  address = "1234 Street Name, City, Country"
  email = "domen.hribernik4@gmail.com"
  phone = "+386 70 700 817"
  twitter = "#"
  facebook = "#"
  github = "https://github.com/domenhribernik"
  name = "Domen Hribernik"

[[menu.main]]
  name = "About"
  weight = 1
  identifier = "About"
  url = "/#about"

[[menu.main]]
  name = "Projects"
  weight = 2
  identifier = "Projects"
  url = "/#projects"

[[menu.main]]
  name = "Contact"
  weight = 3
  identifier = "Contact"
  url = "/#signup"

