// Invariant checks over the committed Beseda content (views/beseda/data/).
//
// These files are generated by tools/beseda/build.py but shipped from git, so
// this suite is the thing standing between a bad rebuild and production. It
// asserts the promises the page relies on: that indices resolve, that the
// schedule never re-dates a published word, and that the attribution required
// by the sources' licences is present.
//
// Run with: node --test tests/
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { glossSegments, wordOfTheDay } from '../components/beseda/logic.js';

const load = (name) =>
    JSON.parse(readFileSync(new URL(`../views/beseda/data/${name}.json`, import.meta.url), 'utf8'));

const words = load('words');
const sentences = load('sentences');
const topics = load('topics');
const daily = load('daily');

test('every file carries its attribution', () => {
    // CC BY-SA obliges us to say where this came from. Removing it is a
    // licence violation, not a tidy-up.
    for (const [name, file] of Object.entries({ words, sentences, topics, daily })) {
        assert.ok(file._license && file._license.length > 40, `${name}.json is missing _license`);
    }
});

test('the epoch is frozen', () => {
    // Moving it re-dates every word anyone has ever been shown.
    assert.equal(daily.epoch, '2026-08-01');
});

test('the schedule covers at least a year ahead', () => {
    assert.ok(daily.days.length >= 365, `only ${daily.days.length} days scheduled`);
});

test('every scheduled day has a word worth showing and a sentence to show it in', () => {
    daily.days.forEach(([wordIndex, sentenceIndices], i) => {
        const word = words.words[wordIndex];
        assert.ok(word, `day ${i} points at missing word ${wordIndex}`);
        assert.ok(word[1] && word[1].trim(), `day ${i} word "${word[0]}" has no gloss`);
        assert.ok(sentenceIndices.length > 0, `day ${i} word "${word[0]}" has no example`);
        for (const s of sentenceIndices) {
            assert.ok(sentences.sentences[s], `day ${i} points at missing sentence ${s}`);
        }
    });
});

test('every sentence span points at a real word', () => {
    for (const [slovene, , spans] of sentences.sentences) {
        for (const [, , wordIndex] of spans) {
            if (wordIndex === -1) continue;
            assert.ok(words.words[wordIndex], `"${slovene}" points at missing word ${wordIndex}`);
        }
    }
});

test('every sentence renders back to its original text', () => {
    for (const sentence of sentences.sentences) {
        const rebuilt = glossSegments(sentence).map((s) => s.text).join('');
        assert.equal(rebuilt, sentence[0]);
    }
});

test('every topic has words, examples, and a name', () => {
    assert.ok(topics.topics.length >= 10);
    for (const topic of topics.topics) {
        assert.ok(topic.id && topic.title && topic.icon, `topic ${topic.id} is incomplete`);
        assert.ok(topic.words.length >= 5, `topic ${topic.id} is too thin to drill`);
        assert.ok(topic.sentences.length > 0, `topic ${topic.id} has no example sentences`);
        for (const wordIndex of topic.words) {
            assert.ok(words.words[wordIndex], `topic ${topic.id} points at missing word ${wordIndex}`);
        }
    }
});

test('a quiz can always find enough wrong answers within a topic', () => {
    // Four-option multiple choice needs three distractors with distinct
    // meanings, otherwise a question has two right answers.
    for (const topic of topics.topics) {
        const glosses = new Set(topic.words.map((i) => words.words[i][1]));
        assert.ok(glosses.size >= 4, `topic ${topic.id} has only ${glosses.size} distinct meanings`);
    }
});

test('the word of the day resolves on the first and last scheduled day', () => {
    const last = new Date(Date.UTC(2026, 7, 1) + (daily.days.length - 1) * 86400000);
    const lastIso = last.toISOString().slice(0, 10);
    for (const iso of ['2026-08-01', lastIso]) {
        const pick = wordOfTheDay(daily, iso);
        assert.ok(pick, `no word for ${iso}`);
        assert.ok(words.words[pick.wordIndex][1]);
    }
});
