//? Shared page glue for the prerendered post pages (views/blog/<slug>/,
//? generated by tools/seo/generate.js). The article itself is static HTML;
//? this only stamps the footer year and drives the reading-progress bar,
//? mirroring the dynamic reader in post.js.

(function () {
    const yearEl = document.getElementById('currentYear');
    if (yearEl) yearEl.textContent = new Date().getFullYear();

    const progressEl = document.getElementById('read-progress');
    if (!progressEl) return;
    const update = () => {
        const doc = document.documentElement;
        const scrollable = doc.scrollHeight - doc.clientHeight;
        const pct = scrollable > 0 ? (doc.scrollTop / scrollable) * 100 : 0;
        progressEl.style.transform = `scaleX(${Math.min(pct, 100) / 100})`;
    };
    window.addEventListener('scroll', update, { passive: true });
    window.addEventListener('resize', update);
    update();
})();
